version: 0.0
os: linux
files:
  - source: /   # Source location in the deployment package
    destination: /var/www/html   # Destination on the instance
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
